name: Manual Approval

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which AWS environment is targeted?'
        required: true
        type: choice
        options:
          - sandbox
          - dev
          - qa
          - uat
          - prod
      microservice:
        description: 'Which microservice is being deployed?'
        required: true
        type: choice
        options:
          - ods.manager
          - ods.extractor
      version:
        description: 'Version of the microservice'
        required: true
        type: string

jobs:
  approval:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ job.status }}  # Capture the job status (Success/Failure)
    steps:
      - name: Manual Approval
        id: manual_approval
        uses: mskrzypczak/action-wait-for-check@v1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_name: "Manual Approval Required"
          conclusion: 'success'  # or 'failure' if you want to fail
          wait_interval: 30 # in seconds (e.g., 30 seconds)
          timeout: 43200 # in seconds (e.g., 12 hours)
          check_description: |
            Approval required to deploy ${{ github.event.inputs.microservice }} (version ${{ github.event.inputs.version }}) to ${{ github.event.inputs.environment }}.